
services:
  ml-service:
    build: ./ml_service
    container_name: ml-service

  llm-service:
    build: ./llm_service
    container_name: llm-service

  api-gateway:
    build: ./api_gateway
    container_name: api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - ml-service
      - llm-service
